import {useEffect,useRef,useId} from 'react';
import {createPortal} from 'react-dom';import errorHandler from '../../utils/errorHandler';import {X,ArrowUpRight,AlertTriangle,Inbox,LoaderCircle,ChevronLeft,ChevronRight} from 'lucide-react';
export function Button({children,variant='primary',loading=false,className='',...props}){return <button className={`button ${variant} ${className}`} {...props} disabled={props.disabled||loading}>{loading&&<LoaderCircle size={16} className="spin"/>}{children}</button>;}
export function IconButton({label,children,...props}){return <button className="icon-button" aria-label={label} title={label} {...props}>{children}</button>;}
export function Input({label,error,className='',...props}){const id=useId();return <label className={'field '+className} htmlFor={id}><span>{label}</span><input id={id} aria-invalid={!!error} aria-describedby={error?id+'-err':undefined} {...props}/>{error&&<small className="error-text" id={id+'-err'}>{error}</small>}</label>;}
export function Select({label,children,...props}){const id=useId();return <label className="field" htmlFor={id}><span>{label}</span><select id={id} aria-label={label} {...props}>{children}</select></label>;}
export function Textarea({label,...props}){const id=useId();return <label className="field" htmlFor={id}><span>{label}</span><textarea id={id} rows={4} {...props}/></label>;}
export function Checkbox({label,...props}){return <label className="check"><input type="checkbox" {...props}/><span>{label}</span></label>;}
export function Toggle(props){return <Checkbox {...props} role="switch"/>;}
export function Card({children,className='',...props}){return <section className={'card '+className} {...props}>{children}</section>;}
export function GlassCard(props){return <Card {...props} className={'glass '+(props.className||'')}/>;}
export function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>;}
export function Avatar({name=''}){return <span className="avatar" aria-label={name}>{name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()||'U'}</span>;}
export function ProgressBar({value=0,label='Progress'}){const n=Math.max(0,Math.min(100,Number(value)||0));return <div className={'progress '+(value>=100?'danger':value>=80?'warning':'')} role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={n}><i style={{width:n+'%'}}/></div>;}
export function StatCard({label,value,caption,icon:Icon}){return <Card className="stat-card"><div className="row between"><span>{label}</span>{Icon&&<Icon size={18}/>}</div><strong>{value??'—'}</strong><small>{caption}</small></Card>;}
export function Modal({open,title,children,onClose}){const ref=useRef(null),id=useId();useEffect(()=>{if(!open)return;const old=document.activeElement;ref.current?.showModal();const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev;old?.focus();};},[open]);if(!open)return null;return createPortal(<dialog ref={ref} className="modal" aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="row between modal-head"><h2 id={id}>{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={20}/></IconButton></div>{children}</dialog>,document.body);}
export function Drawer(props){return <Modal {...props}/>;}
export function ConfirmDialog({open,onClose,onConfirm,loading,title='Delete this item?',description='This cannot be undone.'}){return <Modal open={open} title={title} onClose={onClose}><p className="muted">{description}</p><div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" loading={loading} onClick={onConfirm}>Confirm</Button></div></Modal>;}
export function Loading({label='Loading your workspace…'}){return <div className="state" role="status"><LoaderCircle className="spin" size={26}/><p>{label}</p></div>;}
export function Skeleton(){return <div className="skeleton" aria-label="Loading" role="status"><i/><i/><i/></div>;}
export function EmptyState({title='A fresh start.',description='Your data will appear here when you add your first item.',action}){return <div className="state"><span className="state-icon"><Inbox size={26}/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function ErrorState({error,onRetry}){return <div className="state error-state" role="alert"><AlertTriangle size={25}/><h3>We couldn’t load this.</h3><p>{errorHandler(error)}</p>{onRetry&&<Button variant="secondary" onClick={onRetry}>Try again <ArrowUpRight size={15}/></Button>}</div>;}
export function Pagination({page,total=0,limit=20,onChange}){const count=Math.max(1,Math.ceil(total/limit));return <div className="pagination"><span>{total} results · Page {page} of {count}</span><div className="row"><IconButton label="Previous page" disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={18}/></IconButton><IconButton label="Next page" disabled={page>=count} onClick={()=>onChange(page+1)}><ChevronRight size={18}/></IconButton></div></div>;}
export function Tabs({items,value,onChange}){return <div className="tabs" role="group" aria-label="View selection">{items.map(i=><button key={i.value} aria-pressed={value===i.value} className={value===i.value?'active':''} onClick={()=>onChange(i.value)}>{i.label}</button>)}</div>;}
export function Tooltip({label,children}){return <span title={label} className="tooltip" tabIndex={0}>{children}<span role="tooltip">{label}</span></span>;}
export function Dropdown({label,children}){return <details className="dropdown"><summary>{label}</summary><div className="card">{children}</div></details>;}
export function Toast({children}){return <div role="status" className="toast">{children}</div>;}
export function DatePicker(props){return <Input {...props} type="date"/>;}export function MoneyInput(props){return <Input {...props} type="number" min="0.01" step="0.01"/>;}export function SearchInput(props){return <Input label="Search" {...props} type="search"/>;}
