module.exports = {
  ROLES: { STUDENT: 'student', ADMIN: 'admin' },
  STATUS: { ACTIVE: 'active', INACTIVE: 'inactive', SUSPENDED: 'suspended', PENDING: 'pending' },
  TRANSACTION_TYPES: { INCOME: 'income', EXPENSE: 'expense', TRANSFER: 'transfer' },
  ACCOUNT_TYPES: { CASH: 'cash', BANK: 'bank', WALLET: 'wallet', SAVINGS: 'savings', CREDIT: 'credit', OTHER: 'other' },
  FREQUENCIES: { DAILY: 'daily', WEEKLY: 'weekly', BIWEEKLY: 'biweekly', MONTHLY: 'monthly', QUARTERLY: 'quarterly', YEARLY: 'yearly' },
  BILL_FREQUENCIES: { ONE_TIME: 'one_time', WEEKLY: 'weekly', BIWEEKLY: 'biweekly', MONTHLY: 'monthly', QUARTERLY: 'quarterly', YEARLY: 'yearly' },
  IMPORT_STATUS: { PENDING: 'pending', PROCESSING: 'processing', COMPLETED: 'completed', FAILED: 'failed', CANCELLED: 'cancelled' },
  IMPORT_ROW_STATUS: { PENDING: 'pending', VALID: 'valid', INVALID: 'invalid', IMPORTED: 'imported', SKIPPED: 'skipped', DUPLICATE: 'duplicate' },
  NOTIFICATION_TYPES: {
    BUDGET_ALERT: 'budget_alert',
    BUDGET_EXCEEDED: 'budget_exceeded',
    BILL_REMINDER: 'bill_reminder',
    BILL_OVERDUE: 'bill_overdue',
    GOAL_MILESTONE: 'goal_milestone',
    GOAL_COMPLETED: 'goal_completed',
    IMPORT_RESULT: 'import_result',
    AI_INSIGHT: 'ai_insight',
    SYSTEM: 'system',
    ANNOUNCEMENT: 'announcement'
  },
  ACADEMIC_YEARS: ['freshman', 'sophomore', 'junior', 'senior', 'graduate', 'other'],
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  TOKEN_EXPIRY_HOURS: 1,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCK_DURATION_MINUTES: 30,
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  ALLOWED_CSV_TYPES: ['text/csv', 'application/vnd.ms-excel', 'text/plain'],
  DUPLICATE_THRESHOLD_HOURS: 24,
  DUPLICATE_AMOUNT_TOLERANCE: 0.01,
  NEAR_LIMIT_THRESHOLD: 0.8,
  EXCEEDED_THRESHOLD: 1.0
};